#!/bin/bash

set -e

usage()
{
    echo -e "Usage: `basename $0` configfile.py [--continue-old-run]"
    echo -e "E.g.,: `basename $0` run-configs/M87_test0.py"
    exit 0
}
if [ $# -lt 1 ] || [ $1 = "-h" ] ; then
    usage
fi

TOPDIR=`pwd`

# a good working directory
export WORK_DIR=$HOME/workflow-runs
mkdir -p $WORK_DIR

mkdir -p generated

# generate the dax
export PYTHONPATH=`pegasus-config --python`
./workflow-generator.py $1 $2

# plan and submit the  workflow
pegasus-plan \
    --conf pegasus.conf \
    --dir $WORK_DIR/runs \
    --relative-dir `date +'%Y%m%d_%H%M%S'` \
    --sites condorpool \
    --staging-site cyverse \
    --output-site cyverse \
    --cluster horizontal \
    --force \
    --dax generated/dax.xml
